---
title: Forecasting for Social Good
draft: false
event: "41st International Symposium on Forecasting"
event_url: "https://isf.forecasters.org/"
url_slides: "/slides/isf2021.html"

location: Virtual
summary: "I provide a summary of Forecasting for Social Good initiatives, I elaborate on what is forecasting for social good,  and what attributes makes a forecasting process FGSG."

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2021-06-30T13:40:00Z"
date_end: "2021-06-30T14:00:00Z"
all_day: false
publishdate: "2021-06-29T11:30:00"

categories:
  - conference
tags:
  - forecasting for social good
  - forecasting
lastmod: '2021-06-30T10:30:00'
featured: no
image:
  caption: ''
  focal_point: 'center'
  preview_only: no
projects: []
---

Forecasting plays a critical role in the development of organisational business strategies. Despite a considerable body of research in the area of forecasting, the focus has largely been on the financial and economic outcomes of the forecasting process as opposed to societal benefits. Our motivation in this study is to promote the latter, with a view to using the forecasting process to advance social and environmental objectives such as equality, social justice and sustainability. We refer to such forecasting practices as Forecasting for Social Good (FSG) where the benefits to society and the environment take precedence over economic and financial outcomes. We conceptualise FSG and discuss its scope and boundaries in the context of the "Doughnut theory". We present some key attributes that qualify a forecasting process as FSG: it is concerned with a real problem, it is focused on advancing social and environmental goals and prioritises these over conventional measures of economic success, and it has a broad societal impact. We also position FSG in the wider literature on forecasting and social good practices. We propose an FSG maturity framework as the means to engage academics and practitioners with research in this area. Finally, we highlight that FSG: (i) cannot be distilled to a prescriptive set of guidelines, (ii) is scalable, and (iii) has the potential to make significant contributions to advancing social objectives.

