---
title: Fully funded PhD opportunity on forecasting & global health at Cardiff University, UK.
author: Bahman
date: '2021-11-24'
slug: phd-offer1
categories:
  - conference
tags:
  - phd
  - funding
  - forecasting
  - humanitarian
subtitle: 'A fully funded PhD opportunity at Cardiff University on forecasting in the global health supply chain & humanitarian sector.'
summary: 'Fully funded PhD opportunity to investigate forecasting and machine learning approaches in the family planning supply chain.'
authors: []
lastmod: '2021-11-24T1535:04Z'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
    number_sections: no
---

I am looking for a new PhD student on "Forecasting improvements for better reproductive health and family planning operations in global health supply chains"

## Project Context

Hundreds-of-millions of women in developing countries lack access to contraceptives. Sound inventory/replenishment decisions of contraceptives rely upon accurate demand forecasts; poor forecasts lead to either: (i) poor availability, which results to dropouts and unwanted pregnancies, with serious societal consequences such as poverty; or occasionally (ii) excessive stocks that are not being used and are wasted! Producing good/effective forecasts is very challenging though because of: (i) lack of data availability and data quality issues ; (ii) complex demand and lead-time patterns; (iii) forecasting needs at multiple levels of geographical hierarchies; and (iv) lack of an integrated inventory-forecasting framework. The as-is inventory-forecasting process in developing counties is highly problematic since it cannot address these challenges, resulting in poor decisions. 

## Project aims

This project aims at making a scientific contribution by: (i) creating an innovative forecasting/machine learning approach to accurately forecast demand of contraceptive products (including new products) in the presence of low-quality data; (ii) do so by feature engineering to select variables with high causal power rather than relying on historical consumption only; (iii) strengthen the method by introducing hierarchical & grouping structure of the problem; and (iv) link forecasting to inventory optimisation through the accurate determination of the underlying loss function accounting for both monetary and non-monetary factors. These are suggested aims and there is scope for student to further develop and refine research aims and produce research questions.

## Supervision team

In this 3-4 year project, the PhD-candidate will join an interdisciplinary research team involving scholars from Cardiff business School, [School of Computer Science & Informatics](https://www.cardiff.ac.uk/computer-science) and [United States Agency for International Development](https://www.usaid.gov/global-health/health-areas/family-planning) (USAID).

**Lead supervisor:** [Bahman Rostami-Tabar](https://bahmanrt.com/)

**Co-supervisors:**

- [Prof. Aris Syntetos ](https://www.cardiff.ac.uk/people/view/598321-syntetos-aris), Cardiff Business School
- [Dr. Federico Liberatore](https://www.cardiff.ac.uk/people/view/1721244-liberatore-federico), School of Computer Science and Informatics
- [Glenn Milano](https://www.linkedin.com/in/milano-glenn/), USAID


## Your profile

Applications will be open to International students. You would need first class honours from an excellent university. International students will also need to have satisfied the [English language requirements](https://www.cardiff.ac.uk/study/international/english-language-requirements/postgraduate).

A tentative PhD candidate will be interested in the following topics:

- Forecasting / Time Series Forecasting 
- Machine learning / deep learning
- Supply Chain Management
- Global Health
- Humanitarian Operations
- R (and Python) programming experience

I don't expect that you have studied some topics such as time series analysis, forecasting, machine learning. If you have a solid background in statistics and mathematics, then you’ll pick up the necessary material as required.

## We offer

Cardiff Business School is one of the leading business schools in the UK and has a global reputation for research, teaching and learning. Staff occupy key positions in world-wide academic networks and conduct research which influences a wide audience in Britain and abroad. [Cardiff Business School was ranked sixth across the UK in the 2014 REF](https://www.cardiff.ac.uk/research/impact-and-innovation/quality-and-performance/ref-2014/units-of-assessment/business-and-management-studies).

We help you to :
- become a highly critical scholar
- learn how to conduct research independently 
- publish important studies, making discoveries and create impact
- learn from doing
- become a great research collaborator

We envisage the student spending up to 3 months of time in USAID (Washington DC, USA) to meet with USAID partners to coordinate activities during the development of the model. This will allow gaining additional exposure to “real world challenges” and enhance his/her employability. 

## Apply online

Will be open soon

The deadline to submit your applications will be the end of February 2022.


If you’ve read this far, and think that you have the background described above, then please send me an email (rostami-tabarb[at]cardiff.ac.uk) including your CV.