# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[menu.main]]
  name = "Blog"
  url = "#posts"
  weight = 1
  
[[menu.main]]
  name = "Forecasting for Social Good"
  url = "#fsocialgood"
  weight = 2
  
[[menu.main]]
  name = "Democratising forecasting"
  url = "#democtarisingf"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 5

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 6
  
[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 7

