---
title: "Grouped time series demand forecasting in supply chains"
author: "Mircetica Dejan","Rostami-Tabar Bahman "  , "Nikolicica Svetlana", "Maslarica Marinko"
date: "17/02/2019"
publication_types : ["3"]
publication : "Working paper"
publication_short : "In *WP*"
tags:
- hierarchical aggregation
link: "/papers/GTSF_SC.pdf"
---

Demand forecasting is an essential component of supply chain management. An accurate demand forecast is required at several different levels of a supply chain network to support planning and decision making process in various departments.  In this paper, we investigate the performance of grouped time series forecasting approaches in supply chains. We first evaluate their forecast performance by means of a simulation study and empirical investigation in a multi-echelon distribution network from a major European beverage industry. For the later, the forecasting structure is designed to support managers’ decisions in manufacturing, marketing, finance and logistics. Then, we examine the forecast accuracy of grouped time series combination approaches. Results reveal that combinations produce more accurate forecasts than individual approaches. Moreover, we develop a model to analyse the impact of time series characteristics on the effectiveness of each approach. Results provide insights into the relationship between time series characteristics and the performance of these approaches at the bottom level of the hierarchy. Valuable insights are offered to practitioners and the paper closes with an agenda for further research in this area.
