---
title: Forecasting COVID19 daily cases using phone call data
draft: false
event: 'Logistics Systems Dynamics Group'
event_url: https://www.cardiff.ac.uk/research/explore/research-units/logistics-systems-dynamics-group

location: Virtual
summary: "We will be running a webinar on ‘Forecasting with Multiple Seasonality’. We cover various forecasting models using A&E data."

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2020-11-23T12:00:00Z"
date_end: "2020-11-23T13:00:00Z"
all_day: false
publishdate: "2020-11-20"

categories:
  - CARBS
tags:
  - forecasting
  - R
  - COVID19
lastmod: '2020-11-20T02:20:01-07:00'
featured: no
image:
  caption: ''
  focal_point: 'center'
  preview_only: no
projects: []
---

The need to forecast COVID-19 related variables continues to be pressing as the epidemic unfolds. Different efforts have been made, with compartmental models in epidemiology and statistical models such as AutoRegressive Integrated Moving Average (ARIMA), Exponential Smoothing (ETS) or computing intelligence models. These efforts have proved useful in some instances by allowing decision makers to distinguish different scenarios during the emergency, but their accuracy has been disappointing, forecasts ignore uncertainties and less attention is given to local areas. In this study, we propose a simple Multiple Linear Regression model, optimised to use call data to forecast the number of daily confirmed cases. Moreover, we produce a probabilistic forecast that allows decision makers to better deal with risk. Our proposed approach outperforms ARIMA, ETS and a regression model without call data, evaluated by three point forecast error metrics, one prediction interval and two probabilistic forecast accuracy measures. The simplicity, interpretability and reliability of the model, obtained in a careful forecasting exercise, is a meaningful contribution to decision makers at local level who acutely need to organise resources in already strained health services. We hope that this model would serve as a building block of other forecasting efforts that on the one hand would help front-line personal and decision makers at local level, and on the other would facilitate the communication with other modelling efforts being made at the national level to improve the way we tackle this pandemic and other similar future challenges.