---
title: Forecasting using R
draft: false
#event: 'R / Medicine 2020'
#event_url: https://events.linuxfoundation.org/r-medicine/
location: Gloucestershire Hospitals NHS Foundation Trust, U.K.
summary: "A 2-day workshop on forecasting using R."

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2020-08-13T09:00:00Z"
date_end: "2020-08-14T16:30:00Z"
all_day: false
publishdate: "2020-06-30"

categories:
  - workshop
tags:
  - tidymodels
  - machine learning
lastmod: '2020-06-30T02:20:01-07:00'
featured: no
image:
  caption: '[Illustration by Joseph August Knip on RawPixel](https://www.rawpixel.com/image/2370064/free-illustration-image-flower-vintage-watercolor)'
  focal_point: 'center'
  preview_only: no
projects: [forecasting-r-nhs]
---

Assuming basic knowledge of statistics, participants will be able to do the following tasks when using forecasting to support decision making process in real World:

- Determine what to forecast according to a forecasting process framework;
- Prepare and manipulate data using functions in basic R, tidyverse and lubridate packages in R;
- Identify systematic patterns using time series toolbox in ggplot2 and forecasting related packages in R such as forecast package;
- Produce point forecasts and prediction intervals using R functions in forecasting related packages such as forecast and fable and user defined functions;
- Determine the accuracy of forecasting models using statistical accuracy performance measures for point and prediction intervals;
- Visualize, export and report result for interpretation and insights using RMarkdown.