---
title: Forecasting with Multiple Seasonality
draft: false
event: 'NHS-R community webinars'
event_url: https://nhsrcommunity.com/home/webinars/

location: Virtual
summary: "We will be running a webinar on ‘Forecasting with Multiple Seasonality’. We cover various forecasting models using A&E data."

# Talk start and end times.
#   End time can optionally be hidden by prefixing the line with `#`.
date: "2020-11-25T13:00:00Z"
date_end: "2020-11-25T14:30:00Z"
all_day: false
publishdate: "2020-11-19"

categories:
  - webinar
tags:
  - forecasting
  - R
  - multiple seasonality
lastmod: '2020-11-19T01:20:01-07:00'
featured: no
image:
  caption: ''
  focal_point: 'center'
  preview_only: no
projects: []
---

With the advances in digital technologies, data is recorded more frequently in many sectors including healthcare. For instance, hospitals collect the arrival time for each admission that contains a detail level of temporal granularity. This often results in time series that exhibit multiple seasonality of different lengths.

Traditional approaches such as simple methods, exponential smoothing or ARIMA models are not appropriate for series with multiple seasonal cycles. Forecasting problems involving such series have been increasingly drawing the attention of researchers leading to the development of several approaches.

In this webinar, we demonstrate how to implement these approaches using fable package in R with a real dataset from a hospital.

The [registration](https://www.eventbrite.co.uk/e/nhs-r-webinar-forecasting-with-multiple-seasonality-tickets-126532230307) is open.

