---
title: Democratising forecasting workshop in Uganda
author: Bahman Rostami-Tabar
date: '2019-02-25'
slug: df-in-uganda
categories:
  - Democratising_forecasting
tags:
  - Forecasting
  - R
  - Workshop
header:
  caption: ''
  image: ''
  preview: yes
---

The 5^th^ [demcoratising forecasting workshop](https://www.bahmanrt.com/#democtarisingf)  will take place in [Makerere University Business School](https://mubs.ac.ug/) in April 2019.
Democratising forecasting is an intiaitive lead by Bahman Rostami-Tabar. The aim is to share knownoledge on forecasting and influence relevant practices prioritising the need of population and the society.

Register [here](https://www.eventbrite.co.uk/e/forecasting-using-r-tickets-57419969675)

>Registeration is closed on Friday 5th April 2019 at 02:30 (UK time).

# Prerequisites

- Basic knowledge in statistics;
- No knowledge of forecasting is assumed.
- No prior knowledge of R is assumed.
- Attending the webinar.

Participants must bring their own laptop with a recent version of R and RStudio installed, along with the following packages and their dependencies:

- Download and install R: click [here](https://cloud.r-project.org/)
- Download and install RStudio: click [here](https://www.rstudio.com/products/rstudio/download/#download)

# Program

## Webinar 
  - 08 April 2019
  - Time: 02:30- 03:30 (UK Time)

## Day 1: 23 April 2019

  - R and RStudio Essentials
  - Reports with RMarkdown
  - Data preparation
  - Data manipulation
  - Data visualization

## Day 2: 24 April 2019

  - Forecasting and decision making
  - Time series patterns
  - Forecaster's toolbox: time series graphics, simple forecasting methods, residual diagnostics, accuracy measurement
  
## Day 3: 25 April 2019

- ARIMA models
- Exponential smoothing models
- Regression

# Schedule

- Start: 09:30 a.m.
- End: 04:45 p.m.

## Refreshment breaks

- Morning: 11:15 - 11:30
- Afternoon: 03:30 - 03:45 p.m.
- Lunch: 01:00 p.m. - 02:00 p.m.

