---
title: dfd
author: ''
date: '2020-02-27'
slug: tidy
categories:
  - Forecasting using R workshop
tags:
  - data preperation
  - R
  - Forecasting
  - tidy data
header:
  caption: ''
  image: ''
  preview: yes
---


# Prepare data
## Import data

You can first create a subdirectory called `data` located in your project directory and then download url_dataset="/data/ae.csv" and save it into `data` subdirectory.

The first step in any forecasting project using R is to import data into R. Our data is  stored in the project directory, in a sub directory called *data*. The format of data is `.csv`, so we need to find a function that imports `.csv` files into R. If you don't know which fucntion to use, just *google* it and find an apparopriate function for your data.

We do almost everything in R using functions, a function is a name that is immediately followed by `()`, e.g. `read_csv()`. We need to remeber the name of functions, what they can get as inputs, how they can process inputs and what they give us as outputs. we call inputs `arguments` and outputs `value`. Use help file to see details of `read_csv()`. Type `?read_csv` in the Console.

We use `read_csv()` function from `readr` package which is a part of [tidyverse package](https://www.tidyverse.org/).
If you have not already installed tidyverse package, you need to install it now. Installing a package means bringing it from its server to your computer. Once installed, you need to make it available to your project using `library()` function whenver you open your project, we say load the package.
To install the package, go to Tools -> Install Packages and type tidyverse in the box,  finally click on `Install` button to install it.

The first argument to read_csv() is the path to the `ae.csv` file. you can use an absolute path because you created a project at the beginning and save your data into `data` subdirectory.
There are many other arguments for each fucntion

```{r import_data}
ae <- readr::read_csv("data/ae.csv")
```

It is always useful to check the structure of your data using `class()`. Becasue different fuctions may accept different data structure. It will tell you what is the structure. In our case it is a tibble, a kind of data frame. To know more about data structure see [here]()

You can also check the data type of each variable.


## Ensure your data is tidy

Many organisations work with spredsheets that are not in a tidy format. But what is a tidy format? we don't mean cleaning data here. [Tidy data](https://r4ds.had.co.nz/tidy-data.html) is defined in as:

Any dataset that satisfies the followign criteria is tidy:

* Each variable must have its own column.
* Each observation must have its own row.
* Each value must have its own cell.

Practically, a dataset is tidy if it is in the form of a table(tibble, dataframe) where each column is a seperate variable.

If data is not in tidy format, we need to make it tidy using functions available in the `tidyr` package of tidyverse.

See this presentation for more information about [messy spredsheets](https://www.londonr.org/wp-content/uploads/sites/2/2019/05/Get-good-data-out-of-bad-spreadsheets-with-tidy-tools.pdf)

Please refer to this [link](http://garrettgman.github.io/tidying/) for examples on how to make messy data tidy.

