---
title: Call for Submissions
author: Bahman Rostami-Tabar
date: '2020-01-13'
slug: CFP-FSG
summary: A guide to call for paper submission for forecasting for social good workshop
categories:
  - Forecasting for Social Good
tags:
  - conference
  - forecasting
  - social good
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---


We are now accepting abstracts for oral and poster presentation at the [2^nd^ International Workshop on Forecasting for Social Good](https://www.f4sg.org) sponsored by the International Institute of Forecasters. Both abstracts on academic forecasting research and applications in forecasting practice are welcome. If you are interested, submit your in [Easychair](https://easychair.org/my/conference?conf=f4sg#).

For poster presentation, please upload your poster in PDF format in addition to the abstract. 
 
If you would like to organise a special session or a panel, please contact: Bahman Rostami-Tabar (<rostami-tabarB@cardiff.ac.uk>).


# Important dates:

- Submission deadline: March 20, 2020 
- Notification to authors: March 27, 2020
- Registration deadline: April 15, 2020

# Publications:

Authors of selected papers will be invited to submit full papers to be published in the following journals:

- International Journal of forecasting
A call for papers will be issued at a later date by both journals.

# Keynote speakers:

- [Prof. Spyros Makridakis](https://scholar.google.com/citations?user=hPpgXPMAAAAJ&hl=en), University of Nicosia
- [Prof. Laura Albert](https://directory.engr.wisc.edu/ie/Faculty/Albert_Laura/), University of Wisconsin Madison
- [Dr. Nicholas G. Reich](https://reichlab.io/), UMass Amherst
- [Dr. Leonardo Milano](https://centre.humdata.org/), Centre for Humanitarian Data, United Nations Office for the Coordination of Humanitarian Affairs (OCHA)

# Organisers:

General chairs

- Dr. Bahman Rostami-Tabar (<rostami-tabarb@cardiff.ac.uk>)
- Dr. Michael Porter (<mdp2u@virginia.edu>)
- Prof. Zied Babai (<mohamed-zied.babai@kedgebs.com>)

# About FSG workshop

Following up on a successful workshop in Cardiff, UK and [International Journal of Forecasting's special issue on Forecasting for Social Good](https://forecasters.org/blog/2018/04/12/ijf-forecasting-for-social-good/) we are pleased to announce the 2nd biannual Workshop on Forecasting for Social Good in 11-12 June 2020 at Kedge Business School in Bordeaux, France. 

While there is a growing recognition by agencies, organizations, and governments that data-driven decision-making tools, like forecasting models, can offer significant improvements to the societies they are working to improve, there is not a cohesive body of research that offers guidance on how to best implement, understand, use, and evaluate forecasting methods for societal impact in practice. Furthermore, the research on forecasting for social good has been relatively slow and sporadic, both in academic publications and practical applications. The goal of this workshop is thus to improve the research and practice in issues related to forecasting for social good by: facilitating interactions between practitioners, researchers, and policy makers to develop a cohesive and sustainable network of international collaborations with a focus on issues related to forecasting for social good; promoting the development of new methodology and metrics to address the specific challenges related to forecasting for social good; providing professional development to policy makers; gaining a better understanding of the available data, challenges in data acquisition, and the uncertainty present in the data used to produce forecasts; and, addressing the ethical issues related to the use of forecasting methods for problems that impact society.
